### ISSUE TITLE
_CastError in result.g.dart

### ISSUE THREAD

**Issue by Jonas-Thumbs** [vaetas/datamuse#1]
Sometimes, datamuse returns a result without a 'score'-property. 
Then, an error occurs in result.g.dart, line 11: "type 'NULL' is not a subtype of int". 

I was able to temporarily fix this by changing line 11 in result.g.dart to:
`score: json['score'] ?? 0 as int,`
(I know it is generated code). Maybe you should make 'score' nullable in the Result class?

Thanks in advance.

**Comment by vaetas** [comment]
I've made the `score` for `Result` nullable and published [version 0.3.0 on pub.dev](https://pub.dev/packages/datamuse/versions/0.3.0)

Can you check that this is working for you? You have not provided any result examples that break the code so I am not able to test it.

**Comment by Jonas-Thumbs** [comment]
Thank you very much! It is working perfectly. I'm sorry for not providing an example, this was actually my first bug report on GitHub.
